// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
const SquareVerifier = artifacts.require("Verifier");
// - use the contents from proof.json generated from zokrates steps
const SquareProof = require("proof.json");

contract("Verifier", (accounts) => {
  const account_one = accounts[0];

  describe("Test square verifier", function () {
    beforeEach(async function () {
      this.contract = await Verifier.new({
        from: account_one,
      });
    });

    it("Test verification with correct proof", async () => {
      // TODO
    });

    it("Test verification with incorrect proof", async () => {
      // TODO
    });
  });
});
